### ISSUE TITLE
Stremio Docker Image - Remote Access

### ISSUE THREAD

**Issue by Joeharrison94** [n0bodysec/docker-images#7]
I am having lots if issues geting this to work, I am running this on a VPS and can access the service but no streams work, I can login and access the addons but any attempt to stream results in this:

![image](https://github.com/n0bodysec/docker-images/assets/53116754/b191dcf2-d7d1-4846-88cd-635119320d91)

I have disabled casting in the env vars, please can you explain the process here, I have tried ip and port access as well as through a vpn tunnel and over fqdn and none work.

**Comment by n0bodysec** [comment]
Hello!
This is not a problem with this docker image, but the expected behavior of Stremio Server.

The server has to be accessible via HTTPS, so you need to have a valid SSL certificate. For this same reason, you will need to configure a reverse proxy.

For example, you can use the following configuration:

```
;; A Records
stremio.DOMAIN.TLD.		1	IN	A	THE_IP ; Stremio
stremio-server.DOMAIN.TLD.	1	IN	A	THE_IP ; Stremio Server
```

Then, in your reverse proxy configuration:

```
stremio.DOMAIN.TLD points to stremio:8080 (or 8081 to use the old ui) - With SSL!
stremio-server.DOMAIN.TLD points to stremio:11470 - With SSL!
```

The final step is to enter the Web UI and manually change the URL of the streaming server. You must set it to: `https://stremio-server.DOMAIN.TLD`

**Comment by Joeharrison94** [comment]
So in this scenario - expose the port to 11470 

here is my compose (Swag reverse proxy)
```yaml
  stremio
    container_name: stremio
    image: n0bodysec/stremio
    environment:
      WORKDIR: /srv/stremio
      APPLY_PATCHES: 1
      FIX_UNSUPPORTED_MEDIA: 1
      NO_CORS: 1
      CASTING_DISABLED=: 1
    ports:
      - '11470:11470'
      - '12470:12470'
      - '8080:8080'
      - '8081:8081'
    networks:
      - proxy_net
    volumes:
      - $DOCKERDIR/stremio/data:./data/:/root/.stremio-server
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/web/patches.js:ro
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/shell/patches.js:ro
      - $DOCKERDIR/stremio/files/patches:/srv/stremio/patches:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - swag=enable
      - swag_address=stremio
      - swag_port=11470
      - swag_proto=http
      - swag_url=stremio.*
 ```

So in this scenario I go to stremio.domain.com and this will be directed through swag to the container, which gives access to services on 11470, are you saying I must access this over 8080 to use this server I cant use web.stremio.com and point it to my server?

Also I am a little unsure as the stremio docs make it a little unclear, if you run the docker container, in my case this one with CASTING_DISABLED on, as the vps should be a passthrough to the client for it to handle the heavy lifting. Why would you need the web portion if you can use the web.stremio.com one or am I missing something. I cant seem to see how the components hang together as they all have the same ui.

Thanks for the quick response also, I appreciate it.

**Comment by Joeharrison94** [comment]
also is there a way to install addons from third parties to the this image?

**Comment by n0bodysec** [comment]
> Thanks for the quick response also, I appreciate it.

You are welcome!

I assumed you were trying to use Stremio Web self-hosted in conjunction with Stremio-Server, since this docker image provides both services. Yes, you can use the official Stremio Web instance (https://web.stremio.com) or any other instance.

If you are interested in self-hosting the Stremio server only, then I recommend you the official Stremio image: https://github.com/Stremio/server-docker.


> also is there a way to install addons from third parties to the this image?

Sure! I added support for autoinstall. See https://github.com/n0bodysec/docker-images/issues/5.

I hope this answers all your questions.

**Comment by Joeharrison94** [comment]
So I only need to expose the 11470 port via the reverse proxy? I would assume that would be http from the proxy to the stremio port? Then I have one more question, I cant quite get this working when I access the stremio.domain.com it redirects to ```
https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2Fstremio.domain.com#/``` this is inccorect as it prefills http into the streaming server, why also does it go to app.strem.io ?

**Comment by Joeharrison94** [comment]
```https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2Fstremio.domain.com#/```

if this is updated to 
```https://app.strem.io/shell-v4.4/?streamingServer=https%3A%2F%2Fstremio.domain.com#/```

then I can do docker logs and see the attempt, but it is trying to cast it even though I set it to disabled?

**Comment by Joeharrison94** [comment]
I updated the set url js to set it statically:
```
    // Setting the streaming server URL to a static value
    const staticServerUrl = 'https://stremio.domain.com/';
    console.log(`Setting streaming server url to ${staticServerUrl}`);
    setStreamingServer(staticServerUrl);

```

however it appears that the container is loading it.

compose:

```yaml
  stremio:
    container_name: stremio
    image: n0bodysec/stremio
    hostname: stremio
    environment:
      WORKDIR: /srv/stremio
      APPLY_PATCHES: 1
      FIX_UNSUPPORTED_MEDIA: 1
      NO_CORS: 1
      CASTING_DISABLED: 1
    ports:
      - '11470:11470'
      - '12470:12470'
      - '8080:8080'
      - '8081:8081'
    networks:
      - proxy_net
    volumes:
      - $DOCKERDIR/stremio/data:/root/.stremio-server
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/web/patches.js:ro
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/shell/patches.js:ro
      - $DOCKERDIR/stremio/files/patches:/srv/stremio/patches:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - swag=enable
      - swag_address=stremio
      - swag_port=11470
      - swag_proto=http
      - swag_url=stremio.*
```
